### ISSUE TITLE
Transparency in Images

### ISSUE THREAD

**Issue by DanielArnett** [mohammedari/opengl_ros#1]
Hello, I'd like to add transparency to the images I publish from this node. How can I make that change?

Thank you!

**Comment by DanielArnett** [comment]
It turns out I successfully added transparency earlier, but that the ROS image viewer ignores the alpha channel. [I just had to change CV_8UC3 to CV_8UC4, and GL_BGR to GL_BGRA.](https://github.com/DanielArnett/opengl_ros/commit/aa7e310be26c3f64f4f9f5746a87639c7846ab43) 

For some reason though now when I pass an image topic with transparency into the node, I believe OpenGL doesn't recognize the transparency channel.

**Comment by mohammedari** [comment]
Thank you for using my code!

I think your change would work for alpha channel, but my current shader code does not take in account alpha channel for now. 
https://github.com/DanielArnett/opengl_ros/blob/7f1bebe2f990af0070322c3f1a51c57c06afadbd/opengl_ros/shader/fs_color_extraction.glsl#L66

Have you tried to change this line?
I am out now, but i think i can test the code when i am back.

**Comment by DanielArnett** [comment]
Yes, I have gotten the shader to publish transparent images, however when I finished experimenting I could not get it to read transparent inputs to the shader. I will create a simple test so I can show you.

And thank you for making such a wonderful node! It's so fast and easy to use!

**Comment by DanielArnett** [comment]
I got the transparency fully working. The last thing I need to do to complete my project is to upload a second texture to the shader. Do you know how I can do this?

You can see in the below image I am creating two image topics with transparency. The image on the right is where I'm trying to blend the two images. [This is where I'm trying to upload a second texture in the code, but I'm clearly not doing it the right way.](https://github.com/DanielArnett/opengl_ros/blob/4381df96a7b9b81e8eea7fe05e1e255bf76c259e/opengl_ros_lib/src/simple_renderer.cpp#L115)

![Screenshot from 2019-12-05 16-33-40](https://user-images.githubusercontent.com/3029502/70276260-e47d7700-177d-11ea-833a-40423d823b07.png)



If you want to try it you can check out the `image_blending` branch of my code and run `roslaunch opengl_ros transparency_test.launch`.

**Comment by mohammedari** [comment]
Thank you for providing the code! and its nice to hear that alpha channel successfuly goes through to the shader!

For handling a second texture in the shader, you may need to  

- add another texture object for the second texture
https://github.com/DanielArnett/opengl_ros/blob/4381df96a7b9b81e8eea7fe05e1e255bf76c259e/opengl_ros_lib/src/simple_renderer.cpp#L46

- bind a sampler to the texture unit (the index  number should be the same to layer value in AddTexture function); you can bind one sampler to two texture units, so you do not need to create another one.
https://github.com/DanielArnett/opengl_ros/blob/4381df96a7b9b81e8eea7fe05e1e255bf76c259e/opengl_ros_lib/src/simple_renderer.cpp#L173

- set the layer index of the unit to the shader uniform variable
https://github.com/DanielArnett/opengl_ros/blob/4381df96a7b9b81e8eea7fe05e1e255bf76c259e/opengl_ros_lib/src/simple_renderer.cpp#L139

Cheers!

**Comment by DanielArnett** [comment]
It's working! Thank you so much! I have a bug where it crashes every 2nd or 3rd time I run it, but I can debug that. Thank you for your help with OpenGL, this will really help me develop shaders for computer vision. 

![Screenshot from 2019-12-06 15-35-18](https://user-images.githubusercontent.com/3029502/70354706-51584600-183e-11ea-82b7-82071c44a84f.png)

[If anyone stumbles across this here is the commit with blending.](https://github.com/DanielArnett/opengl_ros/tree/1ed4ca56e63488b2b6b1dc7d91b11f96838d7d58)
